name: Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  buildAndDeploy:
    concurrency: ci-${{ github.ref }}
    name: Build and Deploy Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Curl tar.gz
        run: |
          mkdir out
          curl -L https://github.com/DerTyp7214/Portfoio/releases/latest/download/out.tar.gz | tar -xzvf - --strip-components=1 -C ./out

      - name: Replace all urls with rboard.dev
        run: |
          find out -type f -exec sed -i 's/https:\/\/dertyp7214.de/https:\/\/rboard.dev/g' {} \;

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
