name: Build and Deploy

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  buildAndDeploy:
    concurrency: ci-${{ github.ref }}
    name: Build and Deploy Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install dependencies and build page
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
