name: Build and Deploy

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  buildAndDeploy:
    concurrency: ci-${{ github.ref }}
    name: Build and Deploy Page
    runs-on: ubuntu-latest
    steps:
      - name: Curl tar.gz
        run: |
          curl -L https://github.com/DerTyp7214/Portfoio/releases/latest/download/out.tar.gz | tar -xzvf -C ./ --strip-components=1

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
