name: Build CI

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  buildMaster:
    name: Build Ci Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.8.0"

      - name: Install dependencies
        run: yarn

      - name: Deploy
        run: yarn deploy
